regions:
  - North America
  - Europe
  - Asia Pacific
  - Middle East
  - Latin America

global_conferences:
  # CNCF / Kubernetes ecosystem
  - kubecon
  - cloudnativecon
  - gitopscon
  - argocon

  # DevOps / Platform
  - devopsdays
  - platformcon
  - devoxx

  # Linux Foundation
  - open source summit
  - linux security summit
  - openssf
  - supplychain security con

topics:
  - ci/cd
  - cloud native
  - containers
  - continuous delivery
  - gitops
  - devops
  - kubernetes
  - platform engineering
  - policy
  - provenance
  - security
  - slsa
  - static application security testing
  - trust
